Created Header & Logo Components
kryptonum-dev/mindsoulhealer pull request #1
Opened 2024-08-26 06:44 UTC by OliwierSellig

2024-08-27 09:34 UTC, milewskibogumil requested changes

2024-08-27 09:34 UTC, milewskibogumil commented on next/package.json
> +    "rfc": "plop"
Why `rfc`?

2024-08-27 09:34 UTC, milewskibogumil commented on next/package.json
> +  },
What does that do?

2024-08-27 09:34 UTC, milewskibogumil commented on next/src/global/fonts.ts
>  });
You're using a different extensions wrong. You shall specify the other formats (`.ttf` and `.woff` are fallbacks) within the `src` array, not every format individually.
https://nextjs.org/docs/app/api-reference/components/font#src

2024-08-27 09:34 UTC, milewskibogumil commented on next/src/global/global.scss
> +  --visited: #503086;
- Consider adding a variant for the variable name, eg. `--error-400`
- The `--error` variable name was used by me, in order to be able to easily change the `--error` or `--success` HEX based on the `light` or `dark` mode of the section. If it is that case, that should be OK.
- The `--visited` variable tells me nothing

2024-08-27 09:34 UTC, milewskibogumil commented on next/src/global/global.scss
> +  font-family: var(--font-gentiumRegularWOFF2);
The fallback extension for font should be specified within `localFont`. That not a good idea, because now, you're loading all the extension.

2024-08-27 09:34 UTC, milewskibogumil commented on next/src/global/global.scss
> +  letter-spacing: calc(0.4rem / 16);
For `letter-spacing` I would rather specify the value with `em` and without `calc`, so eg. `letter-spacing: 0.025em`.

2024-08-27 09:34 UTC, milewskibogumil commented on next/src/components/global/Header/Header.module.scss
> +  font-family: var(--font-gentiumBoldTTF);
You're importing the fonts wrong. Read [the documentation](https://nextjs.org/docs/app/api-reference/components/font). In that case all you need to do is to specify the `font-weight`, not completely different `font-family`.

2024-08-28 05:02 UTC, OliwierSellig commented on next/package.json
> +  },
The recent version of plop seems to have some problems, it's a simple solution for now for it to work, however, I will try to exclude this and try again without it.

2024-08-28 05:03 UTC, OliwierSellig commented on next/package.json
> +    "rfc": "plop"
Before discovering plop I've always used to type rfc to create a React Component. I've memorized it quite well, that's the reasoning behind this.

2024-08-28 05:07 UTC, OliwierSellig commented on next/src/global/global.scss
> +  letter-spacing: calc(0.4rem / 16);
Got it.

2024-08-28 08:17 UTC, merged